import { readdir } from 'node:fs/promises';
import path from 'node:path';
import { test, expect, preparePage, openProfile } from './fixtures';
test.beforeEach(async ({ page }) => { await preparePage(page); });

test('W20 traces a translation to contradictory captures, retains corrections and restores research history', async ({ page, server }) => {
  const p = await (await page.request.post(`${server.url}/api/profiles`, { data: { name: 'Research record', dictionary: [{
    id: 'word', alien_word: 'tal', english_meaning: 'sky', part_of_speech: 'noun', confidence: null, context: '', examples: [], notes: '', created_at: '2026-09-25T00:00:00.000Z',
  }] } })).json();
  const saved = async () => (await (await page.request.get(`${server.url}/api/profiles/${p.id}`)).json());
  let modelCalls = 0; page.on('request', r => { if (r.url().includes('/api/ai/')) modelCalls++; });
  await openProfile(page, server.url, p.name); await page.locator('[data-tour="dashboard"]').click();
  const panel = page.getByRole('region', { name: 'Research evidence', exact: true });
  await panel.getByLabel('Original observation', { exact: true }).fill('tal');
  await panel.getByLabel('Source context').fill('Pointing at the sky');
  await panel.getByRole('button', { name: 'Capture observation', exact: true }).click();
  await expect.poll(async () => (await saved()).research.observations.length).toBe(1);
  await panel.getByLabel('Assertion to investigate').selectOption('word');
  await panel.getByRole('button', { name: 'Propose hypothesis', exact: true }).click();
  const hypothesis = panel.getByLabel('Hypothesis tal → sky', { exact: true });
  await hypothesis.getByLabel('Evidence observation for tal → sky').selectOption({ label: 'tal' });
  await hypothesis.getByRole('button', { name: 'Link evidence', exact: true }).click();
  await expect.poll(async () => (await saved()).research.links.length).toBe(1);
  await hypothesis.getByLabel('Relationship', { exact: true }).selectOption('contradicts');
  await hypothesis.getByRole('button', { name: 'Link evidence', exact: true }).click();
  await expect(hypothesis).toContainText('Support 1 · Contradiction 1');
  await hypothesis.getByLabel('Decision reason').fill('Retain as a working interpretation');
  await hypothesis.getByRole('button', { name: 'Accept hypothesis', exact: true }).click();
  await expect.poll(async () => (await saved()).research.events.length).toBe(1);
  await hypothesis.getByRole('button', { name: 'Save evidence counts' }).click();
  await expect.poll(async () => (await saved()).research.metrics.length).toBe(1);
  await page.locator('[data-tour="translation"]').click();
  await page.getByPlaceholder('Enter unknown language text to translate…').fill('tal');
  await page.getByTestId('lexical-translation').getByRole('button').click();
  await expect(page.getByRole('region', { name: 'Evidence inspector' })).toContainText('Pointing at the sky');
  const symbolic = page.getByRole('region', { name: 'Symbolic translation', exact: true });
  await symbolic.getByRole('button', { name: 'Analyze symbolically' }).click();
  await expect(symbolic).toContainText('the sky');
  await symbolic.getByRole('button', { name: 'Save derivation to research' }).click();
  await expect.poll(async () => (await saved()).research.analyses.length).toBe(1);
  await page.locator('[data-tour="dashboard"]').click();
  await panel.getByText('tal · resolved · current · revision', { exact: false }).click();
  await panel.getByLabel('Expected English for this run').fill('the sky');
  await panel.getByRole('button', { name: 'Check supplied target' }).click();
  await expect.poll(async () => (await saved()).research.tests.length).toBe(1);
  const capture = panel.getByLabel('Observation tal', { exact: true });
  await capture.locator('summary').click();
  await capture.getByLabel('Revised interpretation').fill('The speaker was pointing at water');
  await capture.getByRole('button', { name: 'Append interpretation' }).click();
  await expect(hypothesis.locator('summary').first()).toContainText('invalidated');
  await expect(panel).toContainText('tal · resolved · stale');
  await expect.poll(async () => (await saved()).research.annotations.length).toBe(1);
  const final = await saved(); expect(final.research.observations[0].text).toBe('tal'); expect(final.research.tests[0].outcome).toBe('matches');
  await hypothesis.screenshot({ path: test.info().outputPath('research-correction.png') });
  await server.restart();
  await openProfile(page, server.url, p.name); await page.locator('[data-tour="dashboard"]').click();
  await expect(panel).toContainText('tal · resolved · stale');
  const exported = await page.request.get(`${server.url}/api/archives/export/${p.id}?revision=${final.revision}&sandbox=false`); expect(exported.ok()).toBe(true);
  await expect.poll(() => readdir(path.join(server.dataDir, 'archive-staging'))).toEqual([]);
  const preview = await page.request.post(`${server.url}/api/archives/inspect`, { data: await exported.body(), headers: { 'Content-Type': 'application/octet-stream' } }); expect(preview.status()).toBe(201);
  const response = await page.request.post(`${server.url}/api/archives/${(await preview.json()).token}/restore`, { data: { mode: 'new' } }); expect(response.status()).toBe(201);
  const restored = (await response.json()).profile;
  expect(restored.research.annotations[0].observation_id).toBe(restored.research.observations[0].id);
  expect(restored.research.tests[0].analysis_id).toBe(restored.research.analyses[0].id);
  expect(restored.research.observations[0].content_sha256).toBe(final.research.observations[0].content_sha256);
  expect(modelCalls).toBe(0);
});
