import { test, expect, preparePage, openProfile, attachJson } from './fixtures';
test.beforeEach(async ({ page }) => { await preparePage(page); });

test('W07 failed session saves recover with the same key, attempts, reveals and completion', async ({ page, server }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const profile = await (await page.request.post(`${server.url}/api/profiles`, { data: { name: 'Practice recovery', is_sandbox: true } })).json();
  await page.route('**/api/profiles/*/mutations', route => route.fulfill({ status: 500, json: { error: 'Injected session save failure' } }));
  await openProfile(page, server.url, profile.name);
  await page.getByRole('button', { name: 'Generate & Start Decoding' }).click();
  const first = page.locator('[data-challenge="number-0"]');
  await first.getByRole('textbox').fill('1cat'); await first.getByRole('button', { name: 'Check', exact: true }).click();
  await expect(first.getByRole('status')).toContainText('Not matched');
  await first.getByRole('textbox').fill('1'); await first.getByRole('button', { name: 'Check', exact: true }).click();
  const second = page.locator('[data-challenge="number-1"]');
  await second.getByRole('button', { name: 'Hint', exact: true }).click();
  await second.getByRole('textbox').fill('２'); await second.getByRole('button', { name: 'Check', exact: true }).click();
  await page.locator('[data-challenge="number-2"]').getByRole('button', { name: 'Reveal answer' }).click();
  await page.getByRole('button', { name: 'Continue to Vocabulary' }).click();
  await page.getByPlaceholder('Meaning?').fill('unfinished');
  await expect(page.getByText('Save failed', { exact: true })).toBeVisible();
  await page.locator('[data-tour="samples"]').click(); await page.locator('[data-tour="sandbox"]').click();
  await expect(page.getByPlaceholder('Meaning?')).toHaveValue('unfinished');
  const recoveryFailure = page.waitForResponse(response => response.url().endsWith('/mutations') && response.status() === 500);
  await openProfile(page, server.url, profile.name);
  await recoveryFailure;
  await expect(page.getByPlaceholder('Meaning?')).toHaveValue('unfinished');
  await expect(page.getByText(/First-attempt unaided matches: 0\/2/)).toBeVisible();
  await expect(page.getByText('Save failed', { exact: true })).toBeVisible(); // Wait for the recovery attempt before removing the failure fixture.
  await page.unroute('**/api/profiles/*/mutations');
  await page.getByRole('button', { name: 'Retry save for Practice recovery' }).click();
  await expect(page.getByText('Saved', { exact: true })).toBeVisible();
  const restored = await (await page.request.get(`${server.url}/api/profiles/${profile.id}`)).json();
  expect(restored.sandbox_session.events).toHaveLength(5); expect(restored.dictionary).toHaveLength(3);
  await server.restart(); await openProfile(page, server.url, profile.name);
  await expect(page.getByPlaceholder('Meaning?')).toHaveValue('unfinished');
  await page.getByPlaceholder('Meaning?').fill('WATER!'); await page.getByPlaceholder('Meaning?').press('Enter');
  await page.getByRole('button', { name: 'Continue to Sentences' }).click();
  await page.getByPlaceholder('Your translation...').fill('wa'); await page.getByPlaceholder('Your translation...').press('Enter');
  await expect(page.getByText(/unlisted paraphrase may still be valid/)).toBeVisible();
  await page.getByRole('button', { name: 'Word-by-word help', exact: true }).click();
  await page.locator('[data-challenge="token-0-0"]').getByRole('textbox').fill('a');
  await page.locator('[data-challenge="token-0-0"]').getByRole('button', { name: 'Check', exact: true }).click();
  await expect(page.locator('[data-challenge="token-0-0"]').getByRole('status')).toContainText('Not matched');
  await page.getByPlaceholder('Your translation...').fill('water'); await page.getByPlaceholder('Your translation...').press('Enter');
  await page.getByRole('button', { name: 'Continue to Grammar' }).click();
  await page.getByRole('button', { name: 'Reveal rule' }).click();
  await page.getByRole('button', { name: 'Finish practice' }).click();
  await expect(page.getByRole('heading', { name: /Practice complete/ })).toBeVisible();
  await expect(page.getByText('Saved', { exact: true })).toBeVisible();
  const complete = await (await page.request.get(`${server.url}/api/profiles/${profile.id}`)).json();
  expect(complete.sandbox_session.id).toBe(restored.sandbox_session.id);
  expect(complete.sandbox_session.completed).toBe(true); expect(complete.dictionary).toHaveLength(4);
  expect(complete.samples).toHaveLength(1); expect(complete.grammar_rules).toHaveLength(1);
  await openProfile(page, server.url, profile.name);
  await expect(page.getByRole('heading', { name: /Practice complete/ })).toBeVisible();
  await page.screenshot({ path: test.info().outputPath('sandbox-completed.png'), fullPage: true });
  expect(errors).toEqual([]); await attachJson('sandbox-session.json', { restored, complete, errors });
});

test('W07 malformed generated structure is rejected visibly without storing the raw response', async ({ page, server }) => {
  const profile = await (await page.request.post(`${server.url}/api/profiles`, { data: { name: 'Invalid generation', is_sandbox: true } })).json();
  await page.route('**/api/ai/stream', route => route.fulfill({ contentType: 'text/event-stream', body: 'data: {"token":"{\\"language_name\\":\\"Invalid\\",\\"vocabulary\\":[]}"}\n\ndata: [DONE]\n\n' }));
  await openProfile(page, server.url, profile.name); await page.getByRole('button', { name: 'Generate & Start Decoding' }).click();
  await expect(page.getByRole('alert')).toContainText('Could not start practice');
  await expect(page.getByRole('button', { name: 'Download failed response for diagnostics' })).toBeVisible();
  const stored = await (await page.request.get(`${server.url}/api/profiles/${profile.id}`)).json();
  expect(stored.sandbox_session).toBeUndefined(); expect(stored.dictionary).toHaveLength(0);
  await openProfile(page, server.url, profile.name); await expect(page.getByRole('alert')).toHaveCount(0);
});

test('W07 legacy work remains intact and sessions stay scoped to their profile', async ({ page, server }) => {
  const old = await (await page.request.post(`${server.url}/api/profiles`, { data: { name: 'Legacy practice', is_sandbox: true, dictionary: [{ id: 'old-word', alien_word: 'old', english_meaning: 'past', part_of_speech: 'noun', confidence: 80, context: '', examples: [], notes: '', created_at: new Date().toISOString() }] } })).json();
  const other = await (await page.request.post(`${server.url}/api/profiles`, { data: { name: 'Other practice', is_sandbox: true } })).json();
  await openProfile(page, server.url, old.name);
  await expect(page.getByText(/previous exercise cannot be reconstructed/)).toBeVisible();
  await page.getByRole('button', { name: 'Generate & Start Decoding' }).click();
  await page.getByPlaceholder('Your guess...').first().fill('777');
  await expect(page.getByText('Saved', { exact: true })).toBeVisible();
  await openProfile(page, server.url, other.name);
  await expect(page.getByRole('button', { name: 'Generate & Start Decoding' })).toBeVisible();
  await openProfile(page, server.url, old.name);
  await expect(page.getByPlaceholder('Your guess...').first()).toHaveValue('777');
  const stored = await (await page.request.get(`${server.url}/api/profiles/${old.id}`)).json(); expect(stored.dictionary).toEqual(old.dictionary);
});
