import { test, expect, preparePage, openProfile, attachJson } from './fixtures';

test.beforeEach(async ({ page }) => { await preparePage(page); });

test('W08 duplicate assertions cannot become decoded progress; beliefs are optional and survive reload', async ({ page, server }) => {
  const at = new Date().toISOString();
  const dictionary = Array.from({ length: 50 }, (_, i) => ({ id: `word-${i}`, alien_word: 'tal', english_meaning: 'sky', part_of_speech: 'noun', confidence: 100, context: '', notes: '', examples: [], created_at: at }));
  const profile = await (await page.request.post(`${server.url}/api/profiles`, { data: { name: 'Honest workspace', dictionary, number_system: { base: 8, mappings: { 0: 'zero', 1: 'one', 20: 'twenty', 21: 'extra' }, operators: {} } } })).json();
  await openProfile(page, server.url, profile.name);
  await expect(page.locator('.status-bar')).toContainText('1 assertions');
  await expect(page.locator('.status-bar')).not.toContainText('100%');
  await page.locator('[data-tour="dashboard"]').click();
  await expect(page.getByText('Numbers 1–20 mapped:')).toContainText('2/20');
  await expect(page.getByText('Tested linguistic hypotheses: unavailable')).toBeVisible();
  await expect(page.getByText('AI Field Notes', { exact: true })).toHaveCount(0);
  await page.locator('[data-tour="vocabulary"]').click();
  await page.getByRole('button', { name: '+ Add Word', exact: true }).click();
  await page.getByRole('textbox', { name: 'Alien Word', exact: true }).fill('nesh');
  await page.getByRole('textbox', { name: 'English Meaning', exact: true }).fill('star');
  await expect(page.getByRole('spinbutton', { name: 'User belief (optional, 0–100)' })).toHaveValue('');
  await page.getByRole('button', { name: 'Add to Dictionary', exact: true }).click();
  await expect.poll(async () => (await (await page.request.get(`${server.url}/api/profiles/${profile.id}`)).json()).dictionary.length).toBe(51);
  let saved = await (await page.request.get(`${server.url}/api/profiles/${profile.id}`)).json();
  expect(saved.dictionary[50]).toMatchObject({ confidence: null, user_asserted_confidence: null });
  expect(saved.dictionary[0].confidence).toBe(100);
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.getByRole('spinbutton', { name: 'User belief (optional, 0–100)' }).fill('');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect.poll(async () => (await (await page.request.get(`${server.url}/api/profiles/${profile.id}`)).json()).dictionary[0].confidence).toBeNull();
  await page.locator('[data-tour="grammar"]').click();
  await page.getByPlaceholder('e.g. "Word order is SOV — verb always appears last"').fill('Subject precedes the verb');
  await expect(page.getByRole('spinbutton', { name: 'User belief (optional, 0–100)' })).toHaveValue('');
  await page.getByRole('button', { name: '+ Add Rule', exact: true }).click();
  await expect.poll(async () => (await (await page.request.get(`${server.url}/api/profiles/${profile.id}`)).json()).grammar_rules.length).toBe(1);
  const grammar = await (await page.request.get(`${server.url}/api/profiles/${profile.id}`)).json();
  expect(grammar.grammar_rules[0]).toMatchObject({ confidence: null, user_asserted_confidence: null });
  await server.restart(); await openProfile(page, server.url, profile.name);
  saved = await (await page.request.get(`${server.url}/api/profiles/${profile.id}`)).json();
  expect(saved.dictionary[1].confidence).toBe(100);
  expect(saved.dictionary[0].user_asserted_confidence).toBeNull();
  await page.locator('[data-tour="dashboard"]').click();
  await expect(page.getByText('Saved metric history', { exact: true })).toBeVisible();
  await page.screenshot({ path: test.info().outputPath('workspace-evidence.png'), fullPage: true });
  await attachJson('workspace-metrics.json', { snapshots: saved.metric_snapshots, assertions: saved.dictionary.length });
});

test('W08 failed saves do not fabricate history; number ranges, sparse evidence and ties are explicit', async ({ page, server }) => {
  const profile = await (await page.request.post(`${server.url}/api/profiles`, { data: { name: 'Number evidence', number_system: { base: null, mappings: { 1: 'ra', 2: 'ru', 5: 'ka', 6: 'ka ra', 0: 'zero', 21: 'extra' }, operators: {} } } })).json();
  await openProfile(page, server.url, profile.name); await page.locator('[data-tour="numbers"]').click();
  await expect(page.getByText('Insufficient support:', { exact: false })).toBeVisible();
  await expect(page.getByText('Mappings · 4/20', { exact: true })).toBeVisible();
  await page.route('**/api/profiles/*/mutations', route => route.fulfill({ status: 500, json: { error: 'Injected save failure' } }));
  await page.getByRole('textbox', { name: 'Number 7 mapping', exact: true }).fill('ka ru');
  await expect(page.getByText('Exploratory suggestion: base 5.', { exact: true })).toBeVisible();
  await expect(page.getByText('Save failed', { exact: true })).toBeVisible();
  let saved = await (await page.request.get(`${server.url}/api/profiles/${profile.id}`)).json();
  expect(saved.metric_snapshots).toEqual(profile.metric_snapshots);
  await page.getByRole('textbox', { name: 'Number 10 mapping', exact: true }).fill('ten');
  await page.getByRole('textbox', { name: 'Number 11 mapping', exact: true }).fill('ten ra');
  const lastFailure = page.waitForResponse(response => response.url().endsWith('/mutations') && response.status() === 500);
  await page.getByRole('textbox', { name: 'Number 12 mapping', exact: true }).fill('ten ru');
  await lastFailure;
  await expect(page.getByText('Save failed', { exact: true })).toBeVisible();
  await expect(page.getByText('Tied candidates: 5, 10. No single base suggested.', { exact: true })).toBeVisible();
  await expect(page.getByRole('combobox', { name: 'Working base', exact: true })).toHaveValue('');
  await page.unroute('**/api/profiles/*/mutations');
  await page.getByRole('button', { name: 'Retry save for Number evidence', exact: true }).click();
  await expect(page.getByText('Saved', { exact: true })).toBeVisible();
  saved = await (await page.request.get(`${server.url}/api/profiles/${profile.id}`)).json();
  expect(saved.number_system.base).toBeNull();
  expect(saved.metric_snapshots.at(-1).counts.mappings1To20).toBe(8);
  await page.getByRole('combobox', { name: 'Working base', exact: true }).selectOption('5');
  await expect.poll(async () => (await (await page.request.get(`${server.url}/api/profiles/${profile.id}`)).json()).number_system.base).toBe(5);
  await page.screenshot({ path: test.info().outputPath('number-evidence.png'), fullPage: true });
});
